### ISSUE TITLE
400 Error making backup

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/course-make-backup#2]
This error occurred when trying to make a backup of the gauntlet:

```
course-make-ba… message                   message: Backup course created with id: 11939
course-make-ba… error                     message: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11937/blueprint_templates/default/update_associations | [object Object] stack: Error: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11937/blueprint_templates/default/update_associations | [object Object]
    at Request.request [as _callback] (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\course-make-backup\node_modules\canvas-wrapper\canvas.js:98:37)
    at Request.self.callback (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

It just prints [Object object] instead of the actual object.

**Comment by zachintosh** [comment]
Looks like this occurs when it tries to associate the course.

**Comment by danverde** [comment]
This error occurred while running conversion gauntlet 1

**Comment by danverde** [comment]
Not sure what caused it, but it hasn't happened in a while...
